// Seed medications for new accounts, in the order they're given across the day.
// The eye ointment (3–4x/day) appears once per application time.

export const seedMeds = [
  {
    name: 'Prednisone 5mg',
    dose: '1 tablet',
    timing: 'Morning',
    instructions: 'Give with food. Do not stop abruptly.',
    shortTerm: false,
    endDate: null,
    color: 'coral',
  },
  {
    name: 'Mirtazapine 3.75mg',
    dose: '¼ tablet',
    timing: 'Morning',
    instructions: 'Appetite stimulant.',
    shortTerm: false,
    endDate: null,
    color: 'butter',
  },
  {
    name: 'Doxycycline 50mg',
    dose: '1 tablet',
    timing: 'Morning',
    instructions: 'Give with food. No dairy. Finish all tablets.',
    shortTerm: false,
    endDate: null,
    color: 'mint',
  },
  {
    name: 'Clavamox 125mg',
    dose: '1 tablet',
    timing: 'Morning',
    instructions: 'Give with food. Finish all tablets.',
    shortTerm: false,
    endDate: null,
    color: 'lilac',
  },
  {
    name: 'Clopidogrel 9.375mg',
    dose: '⅛ tablet',
    timing: 'Once daily (morning)',
    instructions: 'Do not discontinue unless directed.',
    shortTerm: false,
    endDate: null,
    color: 'sky',
  },
  {
    name: 'Neo Poly Bac Eye Ointment',
    dose: '¼ inch strip to left eye',
    timing: 'Morning (1st of 4 daily)',
    instructions: 'Apply to left eye only. 3–4 times per day during waking hours.',
    shortTerm: false,
    endDate: null,
    color: 'sand',
  },
  {
    name: 'Buprenorphine 0.075mg',
    dose: '0.15ml into cheek pouch',
    timing: 'Every 8–12 hours',
    instructions: 'Pain relief only. Short-term: 2–3 days post discharge (June 6, 2026).',
    shortTerm: true,
    endDate: '2026-06-09',
    color: 'peach',
  },
  {
    name: 'Neo Poly Bac Eye Ointment',
    dose: '¼ inch strip to left eye',
    timing: 'Midday (2nd of 4 daily)',
    instructions: 'Apply to left eye only.',
    shortTerm: false,
    endDate: null,
    color: 'sand',
  },
  {
    name: 'Neo Poly Bac Eye Ointment',
    dose: '¼ inch strip to left eye',
    timing: 'Afternoon (3rd of 4 daily)',
    instructions: 'Apply to left eye only.',
    shortTerm: false,
    endDate: null,
    color: 'sand',
  },
  {
    name: 'Prednisone 2.5mg',
    dose: '½ tablet',
    timing: 'Evening (8–9pm)',
    instructions: 'Give with food. Do not stop abruptly.',
    shortTerm: false,
    endDate: null,
    color: 'coral',
  },
  {
    name: 'Doxycycline 50mg',
    dose: '1 tablet',
    timing: 'Evening (~12 hrs after morning dose)',
    instructions: 'Give with food. No dairy. Finish all tablets.',
    shortTerm: false,
    endDate: null,
    color: 'mint',
  },
  {
    name: 'Clavamox 125mg',
    dose: '1 tablet',
    timing: 'Evening (~12 hrs after morning dose)',
    instructions: 'Give with food. Finish all tablets.',
    shortTerm: false,
    endDate: null,
    color: 'lilac',
  },
  {
    name: 'Neo Poly Bac Eye Ointment',
    dose: '¼ inch strip to left eye',
    timing: 'Bedtime (4th of 4 daily, if awake)',
    instructions: 'Apply to left eye only. Skip if already asleep — 3 applications is acceptable.',
    shortTerm: false,
    endDate: null,
    color: 'sand',
  },
];
